[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Spring Rest framework"
authors = [{name = "Birddevelper", email = "nikanique.org@gmail.com"}]
dynamic = ["version", "description"]
